### ISSUE TITLE
A couple of wishes

### ISSUE THREAD

**Issue by mrkaban** [SihabSahariar/Zharudar-#1]
Your program is unknown, so there is no trust in it, and the point is not in viruses, but in the fact that users do not understand what it does.

I ran File Cleanup and Memory Cleanup and the hard disk space didn’t change, nor did the amount of RAM used. It is necessary to display to the user exactly what she did, and not just write everything ready.

And yet, making shortcuts to regular Windows programs is not serious. Make work with them through WinAPI inside your interface. Yes, it is difficult, but it will be interesting for users.

**Comment by SihabSahariar** [comment]
Thank you so much for your observation. I'll  try to work on those.
